### ISSUE TITLE
guildMember.settings returns default values until guildMemberAdd run() is fully finished

### ISSUE THREAD

**Issue by Lovinity** [dirigeants/klasa-member-gateway#235]
# Describe the issue
guildMember.settings contains default values until the Klasa guildMemberAdd event has finished executing. This causes problems; guild member settings cannot be used in the guildMemberAdd event.

### Code or steps to reproduce
1. Install klasa-member-gateway plugin.
2. Change default member schema and set default values for some (or all) of the Pieces.
3. Change one (or more) of the settings for a member.
4. Create a guildMemberAdd event, and add this code at the top of the run function:
```
setTimeout(() => {
   console.log(guildMember);
}, 30000);
```
5. Reboot the bot and run it in a way the console can be viewed.
6. Have the member edited in step 3 leave, then re-join, the guild.
7. Before 30 seconds is up, execute command `!eval message.guild.members.resolve(INSERT_MEMBER_SNOWFLAKE_HERE).settings;`; notice default settings are returned and not the actual settings as changed in step 3 for the member.
  --- Bonus: Do it again before the 30 seconds is up and notice again it returns the default settings.
8. When the 30-second timeout is finished, run the command from bot 7 again as soon as possible. Notice now it returns the correct settings.
9. Check the console from when the timeout expired. Notice the console logged the default settings and not the correct ones.

### Expected and actual behavior
**EXPECTED**
When guildMemberAdd executes, I can access the correct member settings right away.

**ACTUAL**
guildMember.settings contains default values, not actual values, until everything in the guildMemberAdd event is finished executing, including timeouts.

### Further details
* I have also tested using guildMember.guild.members.fetch(guildMember.id) within the guildMemberAdd event. It still returns default settings.

- **discord.js version**: discordjs/discord.js#123713305ad5a6aa1e5205a53713494009740aef
- **node.js version**: 12.13.1
- **Klasa version**: dirigeants/klasa#0e9174cab0df7d28f3a7b8ca78b6344fef2611c9
- [ ] I have modified core files.
- [] I have tested the issue on latest master. Commit hash: #2d70de3f8ecd6ee2d5cb282c2aa188723d037a83

**Comment by kyranet** [comment]
Run `member.sync();` and problem solved.
We cannot control how events are emitted nor we can stop the userland `addGuildMember` event from being emitted *until* the sync finishes.

**Comment by Lovinity** [comment]
Thanks! Though that's odd that sync never finishes until after the event is completely finished executing.

**Comment by kyranet** [comment]
It's not odd, it resolves whenever it has finished downloading and patching the data.

**Comment by Lovinity** [comment]
That's how I would expect it to work, but that's not how it's actually working on my end. It does not finish until after guildMemberAdd run() is completely done. I know this because when I don't have any timeouts in that function, the correct settings are available in the eval command almost immediately. However, if I, for example, put a 30 second setTimeout in there, eval always returns default settings until that timeout has fired.

**Comment by kyranet** [comment]
Sounds like you're doing something janky, the behaviour is that upon a GuildMember class instantiation, it queues a background sync, so it'll resolve whenever it resolves, it doesn't depend on anything and much less an event, this happens before the event.

Of course, due to async's nature, it can happen that there's a race condition between the background sync and the forced sync, which is what `settings.sync();` fixes.

**Comment by Lovinity** [comment]
I'm not sure what it is I'm doing that's janky, but then again I've been surprised before by what Klasa does. When I have a moment, I'll run this test on a clean Klasa installation with the plugin and see if I get the same result and I'll report back to you. In the mean time, `await guildMember.settings.sync(true);` did the trick for now.
