### ISSUE TITLE
Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by Puyodead1** [dirigeants/klasa-member-gateway#316]
### Describe the issue
Discord.JS no longer has GuildMemberStore so klasa-member-gateway throws ``Class extends value undefined is not a constructor or null`` error

### Expected and actual behavior
no errors and klasa-member-gateway works as intended, what it actually does is crash and throw the error said above 
### Further details

- **discord.js version**: 12.2.0
- **node.js version**: 14.0.0
- **Klasa version**: master
- [x ] I have modified core files.
- [✓ ] I have tested the issue on latest master. Commit hash: 48e9eed5227a02119cd6082bf66d076006f86fce

**Comment by kyranet** [comment]
This project (and all others) has been on hold as we're working on [Project Blue](https://github.com/dirigeants/Project-Blue). As soon as we're done, we'll start updating Klasa for the long-awaited *Project Red* after of which it'll have an interface that will make all plugins (including this one) work better than ever before.

You are free to fork this repository and make the fixes yourself in the meantime. 👍

**Comment by Puyodead1** [comment]
Okay, thanks for the fast reply!
